spring.application.name=crypto
spring.datasource.url=jdbc:mysql://localhost:3306/blockfoliox
spring.datasource.username=root
spring.datasource.password=aarushi@22

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# Binance Testnet base URL
binance.testnet.baseUrl=https://testnet.binance.vision
encryption.secret.key=blockfoliox$secret$key$32chars!!
etherscan.api.key=TJUXRC7Q3U2I8Q4U22KNYV4K6TX77MCJ4C