server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/blockfoliox?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=your_username
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

encryption.secret=your_secret
etherscan.api.key=your_api_key